# Generated by Django 3.2.18 on 2023-02-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='amount',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
