# Generated by Django 3.2.18 on 2023-02-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_auto_20230227_0856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
